import Tiptap from "@/components/Tiptap";
import { useGlobalShortcut } from "@/hooks/tauri/shortcuts";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useCallback } from "react";

const Home: NextPage = () => {
  const shortcutHandler = useCallback(() => {
    console.log("Ctrl+P was pressed!");
  }, []);
  useGlobalShortcut("CommandOrControl+P", shortcutHandler);

  return (
    <div className="flex min-h-screen flex-col bg-white">
      <Head>
        <title>Noter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-1 flex-col items-center justify-center py-8">
        <h1 className="m-0 text-center text-6xl">
          Vítej v <span className="text-blue-600">Noter</span>u{" "}
        </h1>

        <p className="my-12 text-center text-2xl leading-9">
          Tvůj kamarád při vytváření{" "}
          <code className="rounded-md bg-gray-200 p-2 font-mono text-xl text-blue-700">
            poznámek
          </code>
        </p>
        <div className="container">
          <Tiptap />
        </div>
      </main>

      <footer className="flex flex-1 flex-grow-0 items-center justify-center border-t border-gray-200 py-4">
        <div>
          <a
            href="https://tauri.app/"
            target="_blank"
            rel="noopener noreferrer"
            className="flex flex-grow items-center justify-center p-4"
          >
            Powered by{" "}
            <span className="ml-2 h-6">
              <Image
                src="/tauri_logo_light.svg"
                alt="Vercel Logo"
                height={24}
                width={78}
              />
            </span>
          </a>
        </div>
      </footer>
    </div>
  );
};

export default Home;
